[package]
name = "rusty_boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[env]
RUST_BACKTRACE=1

[dependencies]
raylib = { version = "3.7" }
